//  Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: rest-jdbc
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2018-09-19
:page-description: Learn how to create a REST service with JAX-RS, JSON-P, mySQL, and Open Liberty.
:page-tags: ['REST', 'MicroProfile', 'microservices']
:page-related-guides: ['rest-intro','rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Creating a RESTful web service with JDBC

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to create a service with mySQL, and Open Liberty.

== What you'll learn

You will learn how to build and test a simple JDBC-REST service with JAX-RS and JSON-P that will expose
the JVM's system properties. The REST service will respond to GET requests made to the URL:

[source,role="no_copy"]
----
http://localhost:9080/Liberty/api/test
----

The service responds to a `GET` request which will return a JSON array back to you. An example of this is

[source,json,role="no_copy"]
----
[{"first_name":"Georgi","last_name":"Facello"},{"first_name":"Bezalel","last_name":"Simmel"},{"first_name":"Parto","last_name":"Bamford"},{"first_name":"Chirstian","last_name":"Koblick"},{"first_name":"Kyoichi","last_name":"Maliniak"},{"first_name":"Anneke","last_name":"Preusig"},{"first_name":"Tzvetan","last_name":"Zielinski"},{"first_name":"Saniya","last_name":"Kalloufi"},{"first_name":"Sumant","last_name":"Peac"},{"first_name":"Duangkaew","last_name":"Piveteau"}]
----

When you create a new REST application the design of the API is important. The JAX-RS APIs could be
used to create JSON-RPC, or XML-RPC APIs, but wouldn't be a RESTful service. A good RESTful service
is designed around the resources that are exposed, and how to create, read, update, and delete the
resources.

The service responds to `GET` requests to the `/System/properties` path. The `GET` request should
return a `200 OK` response that contains all of the JVM's system properties.

include::{common-includes}/gitclone.adoc[]

== Prerequisites

=== Installing and using MySQL
This guide will be unique as it will require some installation and/or prior knowledge. This guide requires a mySQL server and Maven in the machine. 
For this guide: please install the mySQL Community Server from this site: https://dev.mysql.com/downloads/. (Unless you know how to connect to a MySQL database, please install the MySQL workbench too).

Go through the mySQL setup for the server. Please use the legacy encryption for the password, as it is less of a hassle.

*optional* If you have installed the MySQL workbench, you may need to add an additional path in your BASH. In Mac, it will be similar to this on your `.bash_profile`:
```
export PATH=$PATH:/Applications/MySQLWorkbench.app/Contents/MacOS
```

**NOTE** If you have not setup mySQL before, make a root password during the setup, or it will be hard making new users for the mysql database.

Now, testuser and a new password to connect with the mysql server. 
Sign on as root:
----
myuser@mycomputer:~$ mysql -u root -p
----
The `-u` tells mysql that you want to use the user root and the `-p` flag means that the password will provided in the next prompt.

Now the testuser needs to be installed into the mysql server. We will make a new testuser named `mytestuser` and the password `mypassword`:
----
mysql> CREATE USER 'mytestuser'@'localhost' IDENTIFIED BY 'mypassword';
mysql> GRANT ALL PRIVILEGES ON * . * TO 'mytestuser'@'localhost';
mysql> EXIT
----

For now, a sample database given by the MySQL will be used called the Employees. The Employees database can be installed here: https://github.com/datacharmer/test_db. Download the repo, and import the db data into the mysql database. 
----
myuser@mycomputer:~$ git clone https://github.com/datacharmer/test_db
myuser@mycomputer:~$ cd test_db
myuser@mycomputer:~$ mysql -u mytestuser -p < employees.sql
----
The last line will prompt for a password which is `mypassword`. 

=== Installing Maven
Download Maven at https://maven.apache.org/download.cgi. There are dependencies for Maven so please fullfill those dependencies before you do anything else. 

Download the tar.gz version of the guide and extract the tar.gz.

`tar xzvf apache-maven*`

After extracting the folder. Move it into your `/opt` folder, if you choose to:

`sudo mv apache-maven* /opt`

You should always link the bin of the maven so you can use it in BASH using `.bash_profile`(for MAC). 
If you put maven into /opt, you will need to export PATH by invoking:

`export PATH=$PATH/opt/apache-maven-3.5.4/bin`(your version number may vary)

If done correctly, invoking `mvn --version` should give an output similar to this: 
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T13:33:14-05:00)
Maven home: /opt/apache-maven-3.5.4
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

```


== Creating a JAX-RS application

**Note** Everything is based on the `start/` directory of the folder: `guide-JDBC/start`

Create the JAX-RS application class in `src/main/java/io/openliberty/guides/rest/SystemApplication.java` file and write this into it:
[source,java]
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[tags=**;!comment]
----
The `SystemApplication` class extends the `Application` class, which in turn associates all JAX-RS
resource classes in the WAR file with this JAX-RS application, making them available under the common
path specified in the `SystemApplication` class. The `@ApplicationPath` annotation has a
value that indicates the path within the WAR that the JAX-RS application accepts requests from.

== Creating the JDBC resource

Next, create the JDBC resource class in the `src/main/java/io/openliberty/guides/rest/TestResource.java` file:
[source,java]
----
include::finish/src/main/java/io/openliberty/guides/rest/TestResource.java[tags=**;!comment]
----

This resource class has quite a bit of code in it, so let's break it down into manageable chunks.

The `@Path` annotation on the class indicates that this resource responds to the `properties` path
in the JAX-RS application. The `@ApplicationPath` annotation in the application class together with
the `@Path` annotation in this class indicates that the resource is available at the `api/test`
path.

JAX-RS maps the HTTP methods on the URL to the methods on the class. The method to call is determined
by the annotations specified on the methods. In the application you are building, an HTTP `GET` request
to the `api/test` path results in the system properties being returned:

The `@GET` annotation on the method indicates that this method is to be called for the HTTP `GET`
method. The `@Produces` annotation indicates the format of the content that will be returned, the
value of the `@Produces` annotation will be specified in the HTTP `Content-Type` response header.
For this application, a JSON structure is to be returned. The desired `Content-Type` for a JSON
response is `application/json` with `MediaType.APPLICATION_JSON` instead of the `String` content type. Using literal code such as `MediaType.APPLICATION_JSON` is better because in the event of a spelling error, a compile failure occurs.

If more help is needed to understand what the Resources do, please consult the 
https://www.openliberty.io/guides/rest-intro.html guide

The method body does the following actions:

. It uses a String to determine what statement to query to database.
. The var `conn` tries to make a connection to using the path to mysql using the credentials of the db_url, user, and pass
. `stmt` then creates a statment to send to the database and tries to execute it
. If there are results from the database, a JsonObject will be created and then be added to the JsonObjectArray.
. The JsonObject is then built and returned. 
. If any part of the statment did not work, then it will go to the Exception and put it on the JsonArray

Once you are done with it. You need to invoke Maven to clean and install the package. 

=== Builing and running the application:
To build the application, run Maven clean and install on your `start` directory. It should have a `pom.xml` file in it:
`mvn clean install`

Next, run the Maven goal:

`mvn liberty:run-server`

This goal starts an Open Liberty instance from your `pom.xml` file. 

You can see if it works by invoking:
http://localhost:9080/Liberty/api/test

Press `Ctrl+C` on the terminal to exit the console of OpenLiberty. 

== Great work! You're done!

You developed a REST service by using JAX-RS, JSON-P, and Liberty.

include::{common-includes}/finish.adoc[]
