//  Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: rest-jdbc
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2018-09-19
:page-description: Learn how to create a REST service with JAX-RS, JSON-P, mySQL, and Open Liberty.
:page-tags: ['REST', 'MicroProfile', 'microservices']
:page-related-guides: ['rest-intro','rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Creating a RESTful web service with JDBC

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to create a service with mySQL, and Open Liberty.

== What you'll learn

You will learn how to build and test a simple JDBC-REST service with JAX-RS and JSON-P that will expose
the JVM's system properties. The REST service will respond to GET requests made to the URL:

[source,role="no_copy"]
----
http://localhost:9080/Liberty/api/test
----

The service responds to a `GET` request which will return a JSON array back to you. An example of this is

[source,json,role="no_copy"]
----
[{"first_name":"Georgi","last_name":"Facello"},{"first_name":"Bezalel","last_name":"Simmel"},{"first_name":"Parto","last_name":"Bamford"},{"first_name":"Chirstian","last_name":"Koblick"},{"first_name":"Kyoichi","last_name":"Maliniak"},{"first_name":"Anneke","last_name":"Preusig"},{"first_name":"Tzvetan","last_name":"Zielinski"},{"first_name":"Saniya","last_name":"Kalloufi"},{"first_name":"Sumant","last_name":"Peac"},{"first_name":"Duangkaew","last_name":"Piveteau"}]
----

When you create a new REST application the design of the API is important. The JAX-RS APIs could be
used to create JSON-RPC, or XML-RPC APIs, but wouldn't be a RESTful service. A good RESTful service
is designed around the resources that are exposed, and how to create, read, update, and delete the
resources.

The service responds to `GET` requests to the `/System/properties` path. The `GET` request should
return a `200 OK` response that contains all of the JVM's system properties.

include::{common-includes}/gitclone.adoc[]

== Prerequisites

This guide will be unique as it will require some installation and/or prior knowledge. This guide requires a mySQL server in the machine. 
For this guide: please install the mySQL Community Server from this site: https://dev.mysql.com/downloads/. Unless (you know how to connect to a MySQL database, please install the MySQL workbench too).

Go through the mySQL setup for the server. Please use the legacy encryption for the password, as it is less of a hassle.

*optional* If you have installed the MySQL workbench, you may need to add an additional path in your BASH. In Mac, it will be similar to this on your `.bash_profile`:
```
export PATH=$PATH:/Applications/MySQLWorkbench.app/Contents/MacOS
```

**NOTE** If you have not setup mySQL before, make a root password during the setup, or it will be hard making new users for the mysql database.

Now, we are going to make a new testuser and a new password for this instance. 
Sign on as root:
----
myuser@mycomputer:~$ mysql -u root -p
----
The -u tells mysql that you want to use the user root and the -p flag means that the password will provided in the next prompt.

Now the testuser needs to be installed into the mysql server. We will make a new testuser named `mytestuser` and the password `mypassword`:
----
mysql> CREATE USER 'mytestuser'@'localhost' IDENTIFIED BY 'mypassword';
mysql> GRANT ALL PRIVILEGES ON * . * TO 'mytestuser'@'localhost';
mysql> EXIT
----

For now, the database that will be used is the employee. The employee database can be installed here: https://github.com/datacharmer/test_db. Download the repo, and import the db data into the mysql database. 
----
myuser@mycomputer:~$ git clone https://github.com/datacharmer/test_db
myuser@mycomputer:~$ cd test_db
myuser@mycomputer:~$ mysql -u mytestuser -p < employees.sql
----
The last line will prompt for a password which is `mypassword` that we just made. 

== Creating a JAX-RS application

JAX-RS has two key concepts for creating REST APIs. The most obvious is the resource itself, which is
modelled as a class. The second is a JAX-RS application, which groups all exposed resources under a
common path. You can think of the JAX-RS application as a wrapper for all your resources. Having a
single JAX-RS application is common, although multiple are possible.

Create the JAX-RS application class in the `src/main/java/io/openliberty/guides/rest/SystemApplication.java` file:
[source,java]
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[tags=**;!comment]
----
The `SystemApplication` class extends the `Application` class, which in turn associates all JAX-RS
resource classes in the WAR file with this JAX-RS application, making them available under the common
path specified in the `SystemApplication` class. The `@ApplicationPath` annotation has a
value that indicates the path within the WAR that the JAX-RS application accepts requests from.

== Creating the JDBC resource

Create the JDBC resource class in the `src/main/java/io/openliberty/guides/rest/TestResource.java` file:
[source,java]
----
include::finish/src/main/java/io/openliberty/guides/rest/TestResource.java[tags=**;!comment]
----

This resource class has quite a bit of code in it, so let's break it down into manageable chunks.

The `@Path` annotation on the class indicates that this resource responds to the `properties` path
in the JAX-RS application. The `@ApplicationPath` annotation in the application class together with
the `@Path` annotation in this class indicates that the resource is available at the `api/test`
path.
[source,java,role="no_copy"]
----
include::finish/src/main/java/io/openliberty/guides/rest/TestResource.java[tags=class]
----

JAX-RS maps the HTTP methods on the URL to the methods on the class. The method to call is determined
by the annotations specified on the methods. In the application you are building, an HTTP `GET` request
to the `api/test` path results in the system properties being returned:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/main/java/io/openliberty/guides/rest/TestResource.java[tags=getProperties]
----

The `@GET` annotation on the method indicates that this method is to be called for the HTTP `GET`
method. The `@Produces` annotation indicates the format of the content that will be returned, the
value of the `@Produces` annotation will be specified in the HTTP `Content-Type` response header.
For this application, a JSON structure is to be returned. The desired `Content-Type` for a JSON
response is `application/json` with `MediaType.APPLICATION_JSON` instead of the `String` content type. Using literal code such as `MediaType.APPLICATION_JSON` is better because in the event of a spelling error, a compile failure occurs.

If more help is needed to understand what the Resources do, please consult the 
https://www.openliberty.io/guides/rest-intro.html guide

The method body does the following actions:

. It uses a String to determine what statement to query to database.
. The var `conn` tries to make a connection to using the path to mysql using the credentials of the db_url, user, and pass
. `stmt` then creates a statment to send to the database and tries to execute it
. If there are results from the database, a JsonObject will be created and then be added to the JsonObjectArray.
. The JsonObject is then built and returned. 
. If any part of the statment did not work, then it will go to the Exception and put it on the JsonArray


== Testing the service

You could test this service manually by starting a server and pointing a web browser at the
`\http://localhost:9080/Liberty/rest/test` URL. Automated tests are a much better
approach because they will trigger a failure if a change introduces a bug. JUnit and the JAX-RS Client
API provide a very simple environment to test the application.

You can write tests for the individual units of code outside of a running application server, or they
can be written to call the application server directly. In this example, you will create a test that
does the latter.

Create the test class in the `src/test/java/it/io/openliberty/guides/rest/EndpointTest.java` file:

[source,java]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=**;!comment]
----

This test class has more lines of code than the resource implementation. This situation is common.
The test method is indicated with the `@Test` annotation.

The test code needs to know some information about the application in order to make requests. The server
port and the application context root are key, and are dictated by the server configuration. While this
information can be hardcoded, it is better to specify it in a single place like the Maven `pom.xml`
file. Open the `pom.xml` file to see how the application information is provided in the file:

[source,xml,indent=0,role="no_copy"]
----
include::finish/pom.xml[tag=appdetails]
----

These Maven properties are then passed to the Java test program as a series of system properties in
the `pom.xml` file:

[source,xml,indent=0,role="no_copy"]
----
include::finish/pom.xml[tag=testsysprops]
----

Getting the values to create a representation of the URL is simple. The test class uses the properties
to get the application details:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=systemProperties]
----

The JAX-RS client can be used to make the REST call and convert the payload to and from a JSON-P
representation. To get the JAX-RS client to do the conversion, the client needs to have the `JsrJsonpProvider`
class registered with it by calling the `register` method and providing the `Class` object for the
`JsrJsonpProvider` class:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=clientSetup]
----

To call the JAX-RS service using the JAX-RS client, you first create a `WebTarget` object by calling
the `target` method providing the URL. To cause the HTTP request to occur first the `request` method
on `WebTarget` and then the `get` method on the returned object need to be called. The `get` method
call is a synchronous call that blocks until a response is received. This call returns a `Response`
object, which can be interrogated to determine whether the request was successful:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=request]
----

The first thing to check is that a `200` response was received. The JUnit `assertEquals` method can
be used for this. The first parameter is the error message that indicates why the test failed. The
second parameter is the expected response code, and the third is the actual response code. It is
important to associate the expected response code with the second parameter and the actual response
with the third parameter. Otherwise, the error messages from JUnit will claim that the actual response
is the expected one, which can cause confusion:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=response]
----

Check the response body to ensure it returned the right information. Since the client and the server
are running on the same machine, it is reasonable to expect that the system properties for the local
and remote JVM would be the same. In this case, an assertion is made that the `os.name` system property
for both JVMs is the same. You could write additional assertions to check for more values:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=body]
----

To rebuild, run the tests, and see that the test passes, run the command: `mvn install`. The Maven
build takes a little longer than before the test existed, but expect to see the following information
in the output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.rest.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.884 sec - in it.io.openliberty.guides.rest.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
assertion to a constant value that doesn't match the `os.name` system property.

== Great work! You're done!

You developed a REST service by using JAX-RS, JSON-P, and Liberty.

include::{common-includes}/finish.adoc[]
